app/models.py
# app/models.py

from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, login_manager


class Employee(UserMixin, db.Model):
    """
    Create an Employee table
    """

    # Ensures table will be named in plural and not in singular
    # as is the name of the model
    __tablename__ = 'employees'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(60), index=True, unique=True)
    username = db.Column(db.String(60), index=True, unique=True)
    first_name = db.Column(db.String(60), index=True)
    last_name = db.Column(db.String(60), index=True)
    password_hash = db.Column(db.String(128))
    department_id = db.Column(db.Integer, db.ForeignKey('departments.id'))
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    is_admin = db.Column(db.Boolean, default=False)

    @property
    def password(self):
        """
        Prevent pasword from being accessed
        """
        raise AttributeError('password is not a readable attribute.')

    @password.setter
    def password(self, password):
        """
        Set password to a hashed password
        """
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        """
        Check if hashed password matches actual password
        """
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<Employee: {}>'.format(self.username)


# Set up user_loader
@login_manager.user_loader
def load_user(user_id):
    return Employee.query.get(int(user_id))


class Department(db.Model):
    """
    Create a Department table
    """

    __tablename__ = 'departments'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(60), unique=True)
    description = db.Column(db.String(200))
    employees = db.relationship('Employee', backref='department',
                                lazy='dynamic')

    def __repr__(self):
        return '<Department: {}>'.format(self.name)


class Role(db.Model):
    """
    Create a Role table
    """

    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(60), unique=True)
    description = db.Column(db.String(200))
    employees = db.relationship('Employee', backref='role',
                                lazy='dynamic')

    def __repr__(self):
        return '<Role: {}>'.format(self.name)

app/admin/forms.py
# app/admin/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField, ValidationError
from wtforms.validators import DataRequired, Email
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from ..models import Department, Role, Employee


class DepartmentForm(FlaskForm):
    """
    Form for admin to add or edit a department
    """
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    submit = SubmitField('Submit')

class RoleForm(FlaskForm):
    """
    Form for admin to add or edit a role
    """
    name = StringField('Name', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    submit = SubmitField('Submit')

class EmployeeAssignForm(FlaskForm):
    """
    Form for admin to assign departments and roles to employees
    """
    department = QuerySelectField(query_factory=lambda: Department.query.all(),
                                  get_label="name")
    role = QuerySelectField(query_factory=lambda: Role.query.all(),
                            get_label="name")
    submit = SubmitField('Submit')

class EmployeeForm(FlaskForm):
    """
    Form for users to create new account
    """
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    department = QuerySelectField(query_factory=lambda: Department.query.all(),
                                  get_label="name")
    role = QuerySelectField(query_factory=lambda: Role.query.all(),
                            get_label="name")
    submit = SubmitField('Register')

    def validate_email(self, field):
        if Employee.query.filter_by(email=field.data).first():
            raise ValidationError('Email is already in use.')

    def validate_username(self, field):
        if Employee.query.filter_by(username=field.data).first():
            raise ValidationError('Username is already in use.')

app/__init__.py
# app/__init__.py

# third-party imports
from flask import Flask, render_template, abort
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

# local imports
from config import app_config

db = SQLAlchemy()
login_manager = LoginManager()


def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(app_config[config_name])
    app.config.from_pyfile('config.py')
    # app.config['TEMPLATES_AUTO_RELOAD'] = True
    # app.run(debug=True, use_reloader=True)
    app.jinja_env.cache = {}
    app.jinja_env.auto_reload = True
    app.config['TEMPLATES_AUTO_RELOAD'] = True
    app.config['DEBUG'] = True

    Bootstrap(app)
    db.init_app(app)
    login_manager.init_app(app)
    login_manager.login_message = "You must be logged in to access this page."
    login_manager.login_view = "auth.login"
    migrate = Migrate(app, db)

    from app import models

    from .admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)

    @app.errorhandler(403)
    def forbidden(error):
        return render_template('errors/403.html', title='Forbidden'), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('errors/404.html', title='Page Not Found'), 404

    @app.errorhandler(500)
    def internal_server_error(error):
        return render_template('errors/500.html', title='Server Error'), 500

    @app.route('/500')
    def error():
        abort(500)

    return app

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__)

from . import employee_views
from . import department_views
from . import role_views

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
# app/home/views.py

from flask import render_template, abort
from flask_login import login_required, current_user

from . import home


@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index_public.html', title="Welcome")


@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")

# add admin dashboard view
@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    # prevent non-admins from accessing the page
    if not current_user.is_admin:
        abort(403)
    return render_template('home/admin_dashboard.html', title="Dashboard")

app/templates/base_app.html
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Foundation for Sites</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='foundation/css/foundation.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='foundation/css/app.css') }}">
  </head>
  <body>
    <div class="top-bar-container" data-sticky-container>
      <div class="sticky sticky-topbar" data-sticky data-options="anchor: page; marginTop: 0; stickyOn: small;">
          <div class="top-bar">
              <div class="top-bar-left">
                  <ul class="menu">
                      <li class="menu"><a href="{{ url_for('home.homepage') }}">PM25</a></li>
                  </ul>
              </div>
              <div class="top-bar-right">
                  <ul class="menu">
                      {% if current_user.is_authenticated %}
                          <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                          <li><a ><i class="fa fa-user"></i>  Hi, {{ current_user.first_name }} {{ current_user.last_name }}!</a></li>
                      {% else %}
                          <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                          <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                      {% endif %}
                  </ul>
              </div>
          </div>
      </div>
    </div>

<!--    <div class="grid-container">-->

<!--    </div>-->

    <div class="off-canvas-wrapper">
        <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
            <div class="off-canvas position-left reveal-for-large" id="my-info" data-off-canvas data-position="left">
                <div class="row column">
                    <ul class="accordion" data-accordion data-multi-expand="false">
                        {% if current_user.is_authenticated %}
                          {% if current_user.is_admin %}
                              <li class="accordion-item is-active"><a class="accordion-title" data-accordion-item href="{{ url_for('home.admin_dashboard') }}">Dashboard</a></li>
                              <li class="accordion-item is-active"><a class="accordion-title" data-accordion-item href="{{ url_for('admin.list_departments') }}">Departments</a></li>
                              <li class="accordion-item is-active"><a class="accordion-title" data-accordion-item href="{{ url_for('admin.list_roles') }}">Roles</a></li>
                              <li class="accordion-item is-active"><a class="accordion-title" data-accordion-item href="{{ url_for('admin.list_employees') }}">Employees</a></li>
                          {% else %}
                              <li class="accordion-item is-active"><a class="accordion-title" data-accordion-item href="{{ url_for('home.dashboard') }}">Dashboard</a></li>
                          {% endif %}
                      {% endif %}
                    </ul>
<!--                    <div class="row">-->
<!--                      <div class="columns">-->
<!--                        <ul class="accordion" data-accordion>-->
<!--                          <li class="accordion-item is-active" data-accordion-item>-->
<!--                            <a href="#" class="accordion-title">Accordion 1</a>-->
<!--                          </li>-->
<!--                          <li class="accordion-item" data-accordion-item>-->
<!--                            <a href="#" class="accordion-title">Accordion 2</a>-->
<!--                          </li>-->
<!--                          <li class="accordion-item" data-accordion-item>-->
<!--                            <a href="#" class="accordion-title">Accordion 3</a>-->
<!--                          </li>-->
<!--                        </ul>-->
<!--                      </div>-->
<!--                    </div>-->
                </div>
            </div>
            <div class="off-canvas-content" data-off-canvas-content>
                <div class="primary">
                    <div class="row column">
                        <nav aria-label="You are here:" role="navigation" style="margin: 5px;">
                          <ul class="breadcrumbs">
                              {% if current_user.is_admin %}
                                  <li class="disabled">Administrator</li>
                              {% else %}
                                  <li class="disabled">User</li>
                              {% endif %}
                              <li><a href="#">Features</a></li>
<!--                            <li class="disabled">Gene Splicing</li>-->
<!--                            <li>-->
<!--                              <span class="show-for-sr">Current: </span> Cloning-->
<!--                            </li>-->
                          </ul>
                        </nav>
                        {% block body %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script src="{{ url_for('static', filename='foundation/js/vendor/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='foundation/js/vendor/what-input.js') }}"></script>
    <script src="{{ url_for('static', filename='foundation/js/vendor/foundation.js') }}"></script>
    <script src="{{ url_for('static', filename='foundation/js/app.js') }}"></script>
  </body>
</html>

app/templates/base_auth.html
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Foundation for Sites</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='foundation/css/foundation.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='foundation/css/app.css') }}">
  </head>
  <body>
    <div class="top-bar-container" data-sticky-container>
      <div class="sticky sticky-topbar" data-sticky data-options="anchor: page; marginTop: 0; stickyOn: small;">
          <div class="top-bar">
              <div class="top-bar-left">
                  <ul class="menu">
                      <li class="menu"><a href="{{ url_for('home.homepage') }}">PM25</a></li>
                  </ul>
              </div>
              <div class="top-bar-right">
                  <ul class="menu">
                      {% if current_user.is_authenticated %}
                          {% if current_user.is_admin %}
                              <li><a href="{{ url_for('home.admin_dashboard') }}">Dashboard</a></li>
                              <li><a href="{{ url_for('admin.list_departments') }}">Departments</a></li>
                              <li><a href="{{ url_for('admin.list_roles') }}">Roles</a></li>
                              <li><a href="{{ url_for('admin.list_employees') }}">Employees</a></li>
                          {% else %}
                              <li><a href="{{ url_for('home.dashboard') }}">Dashboard</a></li>
                          {% endif %}
                          <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                          <li><a ><i class="fa fa-user"></i>  Hi, {{ current_user.first_name }} {{ current_user.last_name }}!</a></li>
                      {% else %}
                          <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                          <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                      {% endif %}
                  </ul>
              </div>
          </div>
      </div>
    </div>

    <div class="grid-container">
        {% block body %}
        {% endblock %}
    </div>


    <script src="{{ url_for('static', filename='foundation/js/vendor/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='foundation/js/vendor/what-input.js') }}"></script>
    <script src="{{ url_for('static', filename='foundation/js/vendor/foundation.js') }}"></script>
    <script src="{{ url_for('static', filename='foundation/js/app.js') }}"></script>
  </body>
</html>

app/templates/base_foundation.html
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Foundation for Sites</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='foundation/css/foundation.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='foundation/css/app.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='foundation/css/top-bar.css') }}">
  </head>
  <body>
    <div class="top-bar-container" data-sticky-container>
      <div class="sticky sticky-topbar" data-sticky data-options="anchor: page; marginTop: 0; stickyOn: small;">
          <div class="top-bar">
              <div class="top-bar-left">
                  <ul class="menu">
                      <li class="menu"><a href="{{ url_for('home.homepage') }}">PM25</a></li>
                  </ul>
              </div>
              <div class="top-bar-right">
                  <ul class="menu">
                      {% if current_user.is_authenticated %}
                          {% if current_user.is_admin %}
                              <li><a href="{{ url_for('home.admin_dashboard') }}">Dashboard</a></li>
                              <li><a href="{{ url_for('admin.list_departments') }}">Departments</a></li>
                              <li><a href="{{ url_for('admin.list_roles') }}">Roles</a></li>
                              <li><a href="{{ url_for('admin.list_employees') }}">Employees</a></li>
                          {% else %}
                              <li><a href="{{ url_for('home.dashboard') }}">Dashboard</a></li>
                          {% endif %}
                          <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                          <li><a ><i class="fa fa-user"></i>  Hi, {{ current_user.first_name }} {{ current_user.last_name }}!</a></li>
                      {% else %}
                          <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                          <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                      {% endif %}
                  </ul>
              </div>
          </div>
      </div>
    </div>

    <div class="grid-container">

        {% block body %}
        {% endblock %}

    </div>


    <script src="{{ url_for('static', filename='foundation/js/vendor/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='foundation/js/vendor/what-input.js') }}"></script>
    <script src="{{ url_for('static', filename='foundation/js/vendor/foundation.js') }}"></script>
    <script src="{{ url_for('static', filename='foundation/js/app.js') }}"></script>
  </body>
</html>

app/templates/home/admin_dashboard.html
<!-- app/templates/home/admin_dashboard.html -->
{% import "bootstrap/utils.html" as utils %}
{% extends "base_app.html" %}
{% block title %}Departments{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Admin Dashboard</h1>
        <h3 style="text-align:center;">For administrators only!</h3>
        <hr class="intro-divider">
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/home/dashboard.html
<!-- app/templates/home/dashboard.html -->

{% extends "base_app.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<div class="intro-header-dashboard">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1 style="text-align:center;">The Dashboard</h1>
                    <h3 style="text-align:center;">We made it here!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/index_public.html
<!-- app/templates/home/index_public.html -->

{% extends "base_public.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Project Dream Team</h1>
                    <h3>The best company in the world!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}